### ISSUE TITLE
Add an account chooser to header

### ISSUE THREAD

**Issue by devmrfitz** [watson-hex/frontend-collabamigo#72]
Add an account chooser, following the format shown in this design mockup. It should be placed and triggered in a way similar to GMail Desktop's account chooser:
![image](https://user-images.githubusercontent.com/58381523/138439516-dfb3239a-d850-4bc4-8a25-c8e55f79e3f2.png)

Design mockup:
![image](https://user-images.githubusercontent.com/58381523/138089264-1178f8be-bf38-42be-a468-789bd1468e3e.png)

**Comment by sc0rp10n-py** [comment]
Done. Please check and review.

![image](https://user-images.githubusercontent.com/49873605/141662415-9b9c9d3b-1427-4553-8560-6f0122f1d9b2.png)
